chore: remove feature(doc_auto_cfg) (#540)
```rust
error[E0557]: feature has been removed
 --> ...
  |
L | #![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
  |                                      ^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in 1.58.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
  = note: merged into `doc_cfg`
```