feat(sema): implicit bytes literal conversion to bytes dynamic/fixed (#642)
Resolves #640 
When I run solc on the test case the error message was 
```
TypeError: Type literal_string "ab" is not implicitly convertible to expected type bytes1. Literal is larger than the type.
```
Solar was giving 
```
mismatched types
```
Happy to work on making the error more descriptive on another issue. If
so let me know

---------

Co-authored-by: DaniPopes <57450786+DaniPopes@users.noreply.github.com>